[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/supervisor

[program:queue-default]
command=php /var/www/artisan queue:work --queue=default --sleep=3 --tries=3 --max-time=3600
process_name=%(program_name)s_%(process_num)02d
numprocs=2
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stopsignal=TERM
stdout_logfile=/var/log/supervisor/queue-default.log
stderr_logfile=/var/log/supervisor/queue-default-error.log
user=www-data

[program:queue-snmp]
command=php /var/www/artisan queue:work --queue=snmp_polling --sleep=3 --tries=2 --max-time=3600
process_name=%(program_name)s_%(process_num)02d
numprocs=1
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stopsignal=TERM
stdout_logfile=/var/log/supervisor/queue-snmp.log
stderr_logfile=/var/log/supervisor/queue-snmp-error.log
user=www-data

[program:queue-provisioning]
command=php /var/www/artisan queue:work --queue=provisioning --sleep=3 --tries=1 --max-time=3600
process_name=%(program_name)s_%(process_num)02d
numprocs=1
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stopsignal=TERM
stdout_logfile=/var/log/supervisor/queue-provisioning.log
stderr_logfile=/var/log/supervisor/queue-provisioning-error.log
user=www-data

[program:queue-notification]
command=php /var/www/artisan queue:work --queue=notifications --sleep=3 --tries=3 --max-time=3600
process_name=%(program_name)s_%(process_num)02d
numprocs=1
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stopsignal=TERM
stdout_logfile=/var/log/supervisor/queue-notification.log
stderr_logfile=/var/log/supervisor/queue-notification-error.log
user=www-data
